
import re
import pathlib

file_path = pathlib.Path(r'c:\Users\Fahad\Desktop\New folder (2)\Asghar_work\HNS_Deshboard\daily_branch_snapshots.py')
content = file_path.read_text(encoding='utf-8')

# Replacement 1: table_image refactor
table_image_pattern = r'def table_image\(.*?\n(.*?)\n    return saved'
def table_image_sub(match):
    indent = "    "
    new_func = f"""def table_image(
    df: pd.DataFrame,
    title: str,
    out_path: Path,
    rows_per_page: int = 32,
    subtitle: Optional[str] = None,
) -> List[Path]:
    from matplotlib.figure import Figure
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

    saved: List[Path] = []
    if df.empty:
        fig = Figure(figsize=(15, 3.5))
        canvas = FigureCanvas(fig)
        ax = fig.add_subplot(111)
        ax.axis("off")
        ax.text(0.5, 0.6, title, ha="center", va="center", fontsize=20, weight="bold", color="#2C3E50")
        ax.text(0.5, 0.35, "No data available.", ha="center", va="center", fontsize=14, color="#7F8C8D", style='italic')
        if subtitle:
            ax.text(0.5, 0.15, subtitle, ha="center", va="center", fontsize=12, color="#95A5A6")
        save_figure(fig, out_path)
        return [out_path]

    pages = max(1, (len(df) + rows_per_page - 1) // rows_per_page)
    for page in range(pages):
        start = page * rows_per_page
        chunk = df.iloc[start:start + rows_per_page].copy()
        nrows = len(chunk)
        fig_h = max(4.0, 1.5 + (nrows * 0.45))
        fig = Figure(figsize=(15, fig_h))
        canvas = FigureCanvas(fig)
        ax = fig.add_subplot(111)
        ax.axis("off")
        fig.patch.set_facecolor('#F8F9F9')
        
        page_title = title if pages == 1 else f"{{title}} (Page {{page + 1}}/{{pages}})"
        ax.text(0.5, 1.08, page_title, ha="center", va="bottom", fontsize=20, weight="bold", color="#1A1A1A", transform=ax.transAxes)
        if subtitle:
            ax.text(0.5, 1.02, subtitle, ha="center", va="bottom", fontsize=13, color="#5F6368", transform=ax.transAxes)
            
        tbl = ax.table(
            cellText=chunk.values,
            colLabels=list(chunk.columns),
            cellLoc="left",
            colLoc="left",
            loc="center",
            bbox=[0, 0, 1, 0.98] 
        )
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(11)

        header_color = '#1A73E8'
        even_row_color = '#F8F9FA'
        odd_row_color = '#FFFFFF'
        edge_color = '#E8EAED'

        for (r, c), cell in tbl.get_celld().items():
            cell.set_edgecolor(edge_color)
            cell.set_linewidth(0.5)
            if r == 0:
                cell.set_text_props(weight="bold", color="white", fontsize=12)
                cell.set_facecolor(header_color)
            else:
                cell.set_facecolor(even_row_color if r % 2 == 0 else odd_row_color)
                cell.set_text_props(color="#3C4043")
            cell.set_height(0.12)

        ax.text(1.0, -0.05, "Generated by HNS Analytics Dashboard", ha="right", va="top", fontsize=9, color="#9AA0A6", style='italic', transform=ax.transAxes)

        page_path = out_path
        if pages > 1:
            page_path = out_path.with_name(f"{{out_path.stem}}_p{{page + 1}}{{out_path.suffix}}")
        save_figure(fig, page_path)
        saved.append(page_path)
    return saved"""
    return new_func

# Use a simpler single-line regex search to find and replace the subplots calls
content = re.sub(r'fig, ax = plt\.subplots\(figsize=\(15, 3\.5\)\)', 
                 r'from matplotlib.figure import Figure\n        from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas\n        fig = Figure(figsize=(15, 3.5))\n        canvas = FigureCanvas(fig)\n        ax = fig.add_subplot(111)', 
                 content)

content = re.sub(r'fig, ax = plt\.subplots\(figsize=\(15, fig_h\)\)',
                 r'from matplotlib.figure import Figure\n        from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas\n        fig = Figure(figsize=(15, fig_h))\n        canvas = FigureCanvas(fig)\n        ax = fig.add_subplot(111)',
                 content)

# Refactor render_branch_cards subplots
content = re.sub(r'fig, axes = plt\.subplots\(rows, cols, figsize=\(15, max\(4\.5, rows \* 4\.0\)\)\)',
                 r'from matplotlib.figure import Figure\n    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas\n    fig = Figure(figsize=(15, max(4.5, rows * 4.0)))\n    canvas = FigureCanvas(fig)\n    axes = []\n    for j in range(n):\n        ax = fig.add_subplot(rows, cols, j + 1)\n        axes.append(ax)',
                 content)

# Remove the old list-flattening logic for axes since we build it as a list now
content = re.sub(r'if rows == 1:.*?axes = \[ax for row_axes in axes for ax in row_axes\]', 
                 'pass', content, flags=re.DOTALL)

file_path.write_text(content, encoding='utf-8')
print("Successfully refactored plt.subplots calls.")
