
import pathlib

path = pathlib.Path('c:/Users/Fahad/Desktop/New folder (2)/Asghar_work/HNS_Deshboard/daily_branch_snapshots.py')
content = path.read_text(encoding='utf-8')

old_table_image = '''def table_image(
    df: pd.DataFrame,
    title: str,
    out_path: Path,
    rows_per_page: int = 32,
    subtitle: Optional[str] = None,
) -> List[Path]:
    saved: List[Path] = []
    if df.empty:
        fig, ax = plt.subplots(figsize=(15, 3.5))
        ax.axis("off")
        ax.text(0.5, 0.6, title, ha="center", va="center", fontsize=20, weight="bold", color="#2C3E50")
        ax.text(0.5, 0.35, "No data available.", ha="center", va="center", fontsize=14, color="#7F8C8D", style=\'italic\')
        if subtitle:
            ax.text(0.5, 0.15, subtitle, ha="center", va="center", fontsize=12, color="#95A5A6")
        save_figure(fig, out_path)
        return [out_path]

    pages = max(1, (len(df) + rows_per_page - 1) // rows_per_page)
    for page in range(pages):
        start = page * rows_per_page
        chunk = df.iloc[start:start + rows_per_page].copy()
        nrows = len(chunk)
        # Increase figure height multiplier to accommodate larger text padding
        fig_h = max(4.0, 1.5 + (nrows * 0.45))
        fig, ax = plt.subplots(figsize=(15, fig_h))
        ax.axis("off")
        
        # Add a subtle background color to figure
        fig.patch.set_facecolor(\'#F8F9F9\')
        
        page_title = title if pages == 1 else f"{title} (Page {page + 1}/{pages})"
        ax.text(0.5, 1.08, page_title, ha="center", va="bottom", fontsize=20, weight="bold", color="#1A1A1A", transform=ax.transAxes)
        if subtitle:
            ax.text(0.5, 1.02, subtitle, ha="center", va="bottom", fontsize=13, color="#5F6368", transform=ax.transAxes)
            
        tbl = ax.table(
            cellText=chunk.values,
            colLabels=list(chunk.columns),
            cellLoc="left",
            colLoc="left",
            loc="center",
            bbox=[0, 0, 1, 0.98] 
        )
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(11)

        # Style colors - Premium Palette
        header_color = \'#1A73E8\' # Google Blue
        even_row_color = \'#F8F9FA\'
        odd_row_color = \'#FFFFFF\'
        edge_color = \'#E8EAED\'

        for (r, c), cell in tbl.get_celld().items():
            cell.set_edgecolor(edge_color)
            cell.set_linewidth(0.5)
            if r == 0:
                cell.set_text_props(weight="bold", color="white", fontsize=12)
                cell.set_facecolor(header_color)
                cell.PAD = 0.12
            else:
                cell.set_facecolor(even_row_color if r % 2 == 0 else odd_row_color)
                cell.set_text_props(color="#3C4043")
                cell.PAD = 0.12

            # Premium height
            cell.set_height(0.12)

        # Add footer
        ax.text(1.0, -0.05, "Generated by HNS Analytics Dashboard", ha="right", va="top", fontsize=9, color="#9AA0A6", style=\'italic\', transform=ax.transAxes)

        page_path = out_path
        if pages > 1:
            page_path = out_path.with_name(f"{out_path.stem}_p{page + 1}{out_path.suffix}")
        save_figure(fig, page_path)
        saved.append(page_path)
    return saved'''

new_table_image = '''def table_image(
    df: pd.DataFrame,
    title: str,
    out_path: Path,
    rows_per_page: int = 32,
    subtitle: Optional[str] = None,
) -> List[Path]:
    from matplotlib.figure import Figure
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

    saved: List[Path] = []
    if df.empty:
        fig = Figure(figsize=(15, 3.5))
        canvas = FigureCanvas(fig)
        ax = fig.add_subplot(111)
        ax.axis("off")
        ax.text(0.5, 0.6, title, ha="center", va="center", fontsize=20, weight="bold", color="#2C3E50")
        ax.text(0.5, 0.35, "No data available.", ha="center", va="center", fontsize=14, color="#7F8C8D", style=\'italic\')
        if subtitle:
            ax.text(0.5, 0.15, subtitle, ha="center", va="center", fontsize=12, color="#95A5A6")
        save_figure(fig, out_path)
        return [out_path]

    pages = max(1, (len(df) + rows_per_page - 1) // rows_per_page)
    for page in range(pages):
        start = page * rows_per_page
        chunk = df.iloc[start:start + rows_per_page].copy()
        nrows = len(chunk)
        # Increase figure height multiplier to accommodate larger text padding
        fig_h = max(4.0, 1.5 + (nrows * 0.45))
        fig = Figure(figsize=(15, fig_h))
        canvas = FigureCanvas(fig)
        ax = fig.add_subplot(111)
        ax.axis("off")
        
        # Add a subtle background color to figure
        fig.patch.set_facecolor(\'#F8F9F9\')
        
        page_title = title if pages == 1 else f"{title} (Page {page + 1}/{pages})"
        ax.text(0.5, 1.08, page_title, ha="center", va="bottom", fontsize=20, weight="bold", color="#1A1A1A", transform=ax.transAxes)
        if subtitle:
            ax.text(0.5, 1.02, subtitle, ha="center", va="bottom", fontsize=13, color="#5F6368", transform=ax.transAxes)
            
        tbl = ax.table(
            cellText=chunk.values,
            colLabels=list(chunk.columns),
            cellLoc="left",
            colLoc="left",
            loc="center",
            bbox=[0, 0, 1, 0.98] 
        )
        tbl.auto_set_font_size(False)
        tbl.set_fontsize(11)

        # Style colors - Premium Palette
        header_color = \'#1A73E8\' # Google Blue
        even_row_color = \'#F8F9FA\'
        odd_row_color = \'#FFFFFF\'
        edge_color = \'#E8EAED\'

        for (r, c), cell in tbl.get_celld().items():
            cell.set_edgecolor(edge_color)
            cell.set_linewidth(0.5)
            if r == 0:
                cell.set_text_props(weight="bold", color="white", fontsize=12)
                cell.set_facecolor(header_color)
                cell.PAD = 0.12
            else:
                cell.set_facecolor(even_row_color if r % 2 == 0 else odd_row_color)
                cell.set_text_props(color="#3C4043")
                cell.PAD = 0.12

            # Premium height
            cell.set_height(0.12)

        # Add footer
        ax.text(1.0, -0.05, "Generated by HNS Analytics Dashboard", ha="right", va="top", fontsize=9, color="#9AA0A6", style=\'italic\', transform=ax.transAxes)

        page_path = out_path
        if pages > 1:
            page_path = out_path.with_name(f"{out_path.stem}_p{page + 1}{out_path.suffix}")
        save_figure(fig, page_path)
        saved.append(page_path)
    return saved'''

if old_table_image in content:
    print("Found! Replacing...")
    new_content = content.replace(old_table_image, new_table_image)
    path.write_text(new_content, encoding=\'utf-8\')
else:
    # Try with CRLF
    old_crlf = old_table_image.replace(\'\\n\', \'\\r\\n\')
    print("Trying with CRLF...")
    if old_crlf in content:
        print("Found with CRLF! Replacing...")
        new_content = content.replace(old_crlf, new_table_image.replace(\'\\n\', \'\\r\\n\'))
        path.write_text(new_content, encoding=\'utf-8\')
    else:
        print("Not found even with CRLF.")
        # Print a small section to compare
        print("File content slice around expected area:")
        print(repr(content[5500:5800]))
